# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
