# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='title',
            new_name='c_title',
        ),
        migrations.AddField(
            model_name='stock',
            name='e_title',
            field=models.CharField(default='title', max_length=20),
            preserve_default=False,
        ),
    ]
